-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Treningsplan.Object.Day exposing (day, distance, id, workouts)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Treningsplan.InputObject
import Treningsplan.Interface
import Treningsplan.Object
import Treningsplan.Scalar
import Treningsplan.ScalarCodecs
import Treningsplan.Union


{-| -}
day : SelectionSet Int Treningsplan.Object.Day
day =
    Object.selectionForField "Int" "day" [] Decode.int


{-| -}
distance : SelectionSet Int Treningsplan.Object.Day
distance =
    Object.selectionForField "Int" "distance" [] Decode.int


{-| -}
id : SelectionSet String Treningsplan.Object.Day
id =
    Object.selectionForField "String" "id" [] Decode.string


{-| -}
workouts : SelectionSet decodesTo Treningsplan.Object.Workout -> SelectionSet (List decodesTo) Treningsplan.Object.Day
workouts object_ =
    Object.selectionForCompositeField "workouts" [] object_ (identity >> Decode.list)
