-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Treningsplan.Object.IntensityZone exposing (description, id, intensityType, name)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Treningsplan.InputObject
import Treningsplan.Interface
import Treningsplan.Object
import Treningsplan.Scalar
import Treningsplan.ScalarCodecs
import Treningsplan.Union


{-| -}
description : SelectionSet (Maybe String) Treningsplan.Object.IntensityZone
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| -}
id : SelectionSet (Maybe String) Treningsplan.Object.IntensityZone
id =
    Object.selectionForField "(Maybe String)" "id" [] (Decode.string |> Decode.nullable)


{-| -}
intensityType : SelectionSet (Maybe String) Treningsplan.Object.IntensityZone
intensityType =
    Object.selectionForField "(Maybe String)" "intensityType" [] (Decode.string |> Decode.nullable)


{-| -}
name : SelectionSet (Maybe String) Treningsplan.Object.IntensityZone
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)
