-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Treningsplan.Object.Record exposing (duration, id, race)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Treningsplan.InputObject
import Treningsplan.Interface
import Treningsplan.Object
import Treningsplan.Scalar
import Treningsplan.ScalarCodecs
import Treningsplan.Union


{-| -}
duration : SelectionSet Int Treningsplan.Object.Record
duration =
    Object.selectionForField "Int" "duration" [] Decode.int


{-| -}
id : SelectionSet String Treningsplan.Object.Record
id =
    Object.selectionForField "String" "id" [] Decode.string


{-| -}
race : SelectionSet String Treningsplan.Object.Record
race =
    Object.selectionForField "String" "race" [] Decode.string
