-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Treningsplan.Object.Week exposing (days, distance, id, order)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Treningsplan.InputObject
import Treningsplan.Interface
import Treningsplan.Object
import Treningsplan.Scalar
import Treningsplan.ScalarCodecs
import Treningsplan.Union


{-| -}
days : SelectionSet decodesTo Treningsplan.Object.Day -> SelectionSet (List decodesTo) Treningsplan.Object.Week
days object_ =
    Object.selectionForCompositeField "days" [] object_ (identity >> Decode.list)


{-| -}
distance : SelectionSet Int Treningsplan.Object.Week
distance =
    Object.selectionForField "Int" "distance" [] Decode.int


{-| -}
id : SelectionSet String Treningsplan.Object.Week
id =
    Object.selectionForField "String" "id" [] Decode.string


{-| -}
order : SelectionSet Int Treningsplan.Object.Week
order =
    Object.selectionForField "Int" "order" [] Decode.int
