-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Treningsplan.Object.WorkoutIntensity exposing (coefficient, description, distance, id, intensity, metric, name)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Treningsplan.Enum.Metric
import Treningsplan.InputObject
import Treningsplan.Interface
import Treningsplan.Object
import Treningsplan.Scalar
import Treningsplan.ScalarCodecs
import Treningsplan.Union


{-| -}
coefficient : SelectionSet Float Treningsplan.Object.WorkoutIntensity
coefficient =
    Object.selectionForField "Float" "coefficient" [] Decode.float


{-| -}
description : SelectionSet String Treningsplan.Object.WorkoutIntensity
description =
    Object.selectionForField "String" "description" [] Decode.string


{-| -}
distance : SelectionSet Int Treningsplan.Object.WorkoutIntensity
distance =
    Object.selectionForField "Int" "distance" [] Decode.int


{-| -}
id : SelectionSet String Treningsplan.Object.WorkoutIntensity
id =
    Object.selectionForField "String" "id" [] Decode.string


{-| -}
intensity : SelectionSet String Treningsplan.Object.WorkoutIntensity
intensity =
    Object.selectionForField "String" "intensity" [] Decode.string


{-| -}
metric : SelectionSet Treningsplan.Enum.Metric.Metric Treningsplan.Object.WorkoutIntensity
metric =
    Object.selectionForField "Enum.Metric.Metric" "metric" [] Treningsplan.Enum.Metric.decoder


{-| -}
name : SelectionSet String Treningsplan.Object.WorkoutIntensity
name =
    Object.selectionForField "String" "name" [] Decode.string
