-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Treningsplan.Object.WorkoutPart exposing (distance, intensity, metric, order)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Treningsplan.Enum.MetricV2
import Treningsplan.InputObject
import Treningsplan.Interface
import Treningsplan.Object
import Treningsplan.Scalar
import Treningsplan.ScalarCodecs
import Treningsplan.Union


{-| -}
distance : SelectionSet Int Treningsplan.Object.WorkoutPart
distance =
    Object.selectionForField "Int" "distance" [] Decode.int


{-| -}
intensity : SelectionSet decodesTo Treningsplan.Object.Intensity -> SelectionSet decodesTo Treningsplan.Object.WorkoutPart
intensity object_ =
    Object.selectionForCompositeField "intensity" [] object_ identity


{-| -}
metric : SelectionSet Treningsplan.Enum.MetricV2.MetricV2 Treningsplan.Object.WorkoutPart
metric =
    Object.selectionForField "Enum.MetricV2.MetricV2" "metric" [] Treningsplan.Enum.MetricV2.decoder


{-| -}
order : SelectionSet Int Treningsplan.Object.WorkoutPart
order =
    Object.selectionForField "Int" "order" [] Decode.int
