BEGIN;

DROP EXTENSION IF EXISTS "uuid-ossp";
DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS intensity;
DROP TABLE IF EXISTS workout;
DROP TYPE IF EXISTS metric;
DROP TABLE IF EXISTS workout_parts;
DROP TABLE IF EXISTS record;

COMMIT;
