-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Treningsplan.Object exposing (Day(..), IntensityZone(..), Plan(..), Profile(..), Week(..), Workout(..), WorkoutIntensity(..))


type Day
    = Day


type IntensityZone
    = IntensityZone


type Plan
    = Plan


type Profile
    = Profile


type Week
    = Week


type Workout
    = Workout


type WorkoutIntensity
    = WorkoutIntensity
